[package]
name = "benthic_default_assets"
version = "0.2.1"
authors = ["Skyler Clark<skylerjaneclark@gmail.com>"]
description = "Default assets for the benthic project"
license = "AGPL-3.0-or-later"
homepage= "https://benthic-mmo.github.io/"
repository = "https://github.com/benthic-mmo/benthic_default_assets"
edition = "2024"

[lib]
path = "lib.rs"
